[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[scheduled-functions]]
  name = "crawler-all"
  cron = "*/10 * * * *"

[[scheduled-functions]]
  name = "anchor-checker"
  cron = "*/10 * * * *"
