name: Prechained Verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ngr-dev1/prechained-action@v1
        with:
          ecosystem: npm
